title: Karanpal Singh
logo: /assets/img/headshot.png
description: Washington, United States
show_downloads: false
email: palsinghk@gmail.com
linkedin: https://www.linkedin.com/in/karanpal-singh-35955695/
github:
  owner_url: https://github.com/singh-karanpal/datascience
  repository_url: https://github.com/singh-karanpal/datascience
theme: jekyll-theme-minimal