title: Karanpal Singh
logo: /assets/img/headshot.png
description: |
  Data Scientist  <br>
  ğŸ“ Washington, United States  <br>
  ğŸ“§ palsinghk@gmail.com  <br>
  ğŸ”— [LinkedIn](https://www.linkedin.com/in/karanpal-singh-35955695/) <br>
show_downloads: false
email: palsinghk@gmail.com
linkedin: https://www.linkedin.com/in/karanpal-singh-35955695/
github:
  owner_url: https://github.com/singh-karanpal/datascience
  repository_url: https://github.com/singh-karanpal/datascience
theme: jekyll-theme-minimal