title: Karanpal Singh
logo: /assets/img/headshot.png
description: |
  <strong>Contact</strong> <br>
  ğŸ“ Washington, United States  <br>
  ğŸ“§ palsinghk@gmail.com  <br>
  ğŸ”— <a href="https://www.linkedin.com/in/karanpal-singh-35955695/">LinkedIn</a> <br>
show_downloads: false
email: palsinghk@gmail.com
linkedin: https://www.linkedin.com/in/karanpal-singh-35955695/
github:
  owner_url: https://github.com/singh-karanpal/datascience
  repository_url: https://github.com/singh-karanpal/datascience
theme: jekyll-theme-minimal